const actions = {
  SET_STATE: 'user/SET_STATE',
  LOGIN: 'user/LOGIN',
  LOGIN_V2: 'user/LOGIN_V2',
  REGISTER: 'user/REGISTER',
  VERIFY_TOKEN: 'user/VERIFY_TOKEN',
  REQUEST_LOGIN_CODE: 'user/REQUEST_LOGIN_CODE',
  VERIFY_LOGIN_CODE: 'user/VERIFY_LOGIN_CODE',
  RESET_PASSWORD: 'user/RESET_PASSWORD',
  FORGOT_USERNAME: 'user/FORGOT_USERNAME',
  UPDATE_EMAIL: 'user/UPDATE_EMAIL',
  UPDATE_PASSWORD: 'user/UPDATE_PASSWORD',
  CHECKED_TOURS: 'user/CHECKED_TOURS',
  CHECK_TOURS: 'user/CHECK_TOURS',
  CONTACT_US: 'user/CONTACT_US',

  LOAD_CURRENT_ACCOUNT: 'user/LOAD_CURRENT_ACCOUNT',
  LOGOUT: 'user/LOGOUT',
};

export default actions
